### PR TITLE
port: [#3986] Deletes old team projects (#6005)

### PR DESCRIPTION
**Pull request by NahuelPerales**
Fixes # 3986

## Description
To have bot builder JS consistent with other bot builder versions we are removing old teams projects.

## Specific Changes
Deleted folder testing/teams-scenario with its contents.

### CODE REVIEW

**Comment by ceciliaavila** [comment]
If you check on our PRs, we always use the issue number and title. Additionally, this repo has a rule for the titles, check the failing pipeline. For this case, the title should be:
```
port: [#3986] Deletes old team projects (#6005)
```

**Comment by sw-joelmut** [comment]
- The teams-scenarios should be removed from the list [link](https://github.com/southworks/botbuilder-js/blob/DeleteOldTeamsProjects/testing/README.md).
- As for the pr description, you could use a reference from https://github.com/southworks/botbuilder-dotnet/pull/408 or https://github.com/southworks/botbuilder-dotnet/pull/406.
- For the naming branch, we always use the following format
  - southworks/[add|update|delete|fix]/[name of the task]
    - eg. southworks/add/fileupload-sample
  - Always use lowercase and use '-' as a separator
- Regarding reviewers, we always reference the team members to review
  - eg
  - image

**Comment by ceciliaavila** [comment]
Whenever possible, add a **Testing** section to the PR's description including screenshots as evidence.

**Comment by sw-joelmut** [comment]
> If you check on our PRs, we always use the issue number and title. Additionally, this repo has a rule for the titles, check the failing pipeline. For this case, the title should be:
> 
> ```
> port: [#3986] Deletes old team projects (#6005)
> ```

Whenever possible, we use the issue name as the PR title, in some cases we change it to be more specific to the change and not issue title, because it doesn't correlate, or the issue is more high level that the PR change.

**Comment by sw-joelmut** [comment]
When creating a PR, either in this repo or another, all of them have checks to validate the work done in the PR, in this repo is much easier since the checks run automatically, you just need to be sure they all passed. In other cases, we run the pipeline specific to the repo to be sure

**Review by ceciliaavila — CHANGES_REQUESTED** [review]
Please apply the change in the README that Joel suggested and the minor fixes in the PR's description and it'll be good to go.

**Comment by NahuelPerales** [comment]
Was replaced with pr #239

**Pull request closed without merging**
